.env

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -35,6 +35,20 @@ jobs:
             fail_on_empty: false
             sort_keys: false
 
+  create-envfile:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check .env
+        run: |
+          if [ ! -f .env ]; then
+            echo "File not found!"
+            exit 1
+          fi
+
+      - name: Check .env content with cat
+        run: |
+          cat .env
+
   testing:
     runs-on: ubuntu-latest
     needs:  [create-envfile]
